import "../styles/global.css";
export const metadata = {
  title: "PokeSearch",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">{children}</div>
      </body>
    </html>
  );
}
